// Domain Errors - Centralized exports
export { DomainErrorCodes, type DomainErrorCode } from './domain_error_codes.js'
export { PseudoAlreadyTakenError } from './pseudo_already_taken_error.js'
export { PartieNotFoundError } from './partie_not_found_error.js'
export { UnauthorizedPartieAccessError } from './unauthorized_partie_access_error.js'
export { GameNotInProgressError } from './game_not_in_progress_error.js'
export { RoundNotFoundError } from './round_not_found_error.js'
export { RoundAlreadyCompletedError } from './round_already_completed_error.js'
export { UnauthorizedRoundAccessError } from './unauthorized_round_access_error.js'
export { InvalidScoresError } from './invalid_scores_error.js'
