// Domain Errors - Centralized exports
export { DomainErrorCodes, type DomainErrorCode } from './domain_error_codes.js'
export { PseudoAlreadyTakenError } from './pseudo_already_taken_error.js'
export { PartieNotFoundError } from './partie_not_found_error.js'
export { UnauthorizedPartieAccessError } from './unauthorized_partie_access_error.js'
export { GameNotInProgressError } from './game_not_in_progress_error.js'
export { RoundNotFoundError } from './round_not_found_error.js'
export { RoundAlreadyCompletedError } from './round_already_completed_error.js'
export { UnauthorizedRoundAccessError } from './unauthorized_round_access_error.js'
export { InvalidScoresError } from './invalid_scores_error.js'
export { InvalidScoreTypeForServiceError } from './invalid_score_type_for_service_error.js'
export { ScoreValueOutOfRangeError } from './score_value_out_of_range_error.js'
export { SecondaryScoreNameRequiredError } from './secondary_score_name_required_error.js'
export { ChallengerForbiddenInFirstRoundError } from './challenger_forbidden_in_first_round_error.js'
export { ChallengerAlreadyExistsInRoundError } from './challenger_already_exists_in_round_error.js'
export { InsufficientDeficitForChallengerError } from './insufficient_deficit_for_challenger_error.js'
export { OpponentNotFoundForChallengerError } from './opponent_not_found_for_challenger_error.js'
export { UnauthorizedScoreAccessError } from './unauthorized_score_access_error.js'
