# Prometheus Configuration
# W40K Scoring - Monitoring et Alerting
global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s
  external_labels:
    cluster: 'w40k-scoring-dev'
    environment: 'development'

# Règles d'alerting
rule_files:
  - 'alert.rules.yml'

# Configuration d'Alertmanager (optionnel pour plus tard)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ['alertmanager:9093']

# Jobs de scraping
scrape_configs:
  # Prometheus lui-même
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # OpenTelemetry Collector
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888', 'otel-collector:8889']
    scrape_interval: 30s
    metrics_path: /metrics

  # W40K Scoring Application
  - job_name: 'w40k-scoring-app'
    static_configs:
      - targets: ['host.docker.internal:3333']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node Exporter - métriques système
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # cAdvisor - métriques containers
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    metrics_path: /metrics

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: /metrics
    scrape_interval: 60s

# Configuration storage
storage:
  tsdb:
    retention.time: 15d
    retention.size: 10GB
    wal-compression: true
